# the name that your experiment will be grouped under on mlflow
experiment_name: A-baseline

# default parameters for training and eval
model: graph_lam
graph: 1level
hidden_dim: 128
processor_layers: 2
metrics_watch: val_rmse, mse, random_metric
logger: mlflow
lr: 0.001