# the name of the "experiment" on mlflow that your run(s) will be grouped under
# change this to something that describes what you'll be working on (for
# example what the parameter study is about)
logger_project: A-baseline

# change this to the path of the virtual environment where you have installed
# neural-lam and dependencies (creating the venv might become part of the dvc
# pipeline in future, but for now you have to do this manually)
venv_path: /dcai/users/denlef/git-repos/mllam/mllam-exps/.venv

# default parameters for training and eval
model: graph_lam
graph: 1level
hidden_dim: 128
processor_layers: 2
metrics_watch: val_rmse, mse, random_metric
logger: mlflow
lr: 0.001