# the name that your experiment will be grouped under on mlflow
experiment_name: A-baseline

# change this to the path of the virtual environment where you have installed
# neural-lam and dependencies (creating the venv might become part of the dvc
# pipeline in future, but for now you have to do this manually)
venv_path: /dcai/users/denlef/git-repos/mllam/mllam-exps/.venv

# default parameters for training and eval
model: graph_lam
graph: 1level
hidden_dim: 128
processor_layers: 2
metrics_watch: val_rmse, mse, random_metric
logger: mlflow
lr: 0.001